# Generated by Django 5.0.1 on 2024-01-18 20:35

import django.db.models.deletion
import fidele.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='ville', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fidele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qlook_id', models.CharField(default=fidele.models.qlook, editable=False, max_length=100, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=100, null=True)),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('MARIE', 'MARIE'), ('CELIBATAIRE', 'CELIBATAIRE'), ('CONCUBINAGE', 'CONCUBINAGE'), ('UNION LIBRE', 'UNION LIBRE'), ('VEUF ', 'VEUF')], max_length=100, null=True)),
                ('signe', models.TextField(blank=True, default='description du fidele', max_length=500, null=True)),
                ('nbr_enfants', models.IntegerField(blank=True, default='00000000', null=True)),
                ('contry', models.CharField(blank=True, choices=[("Côte d'Ivoire", "Côte d'Ivoire"), ('France', 'France'), ('Congo', 'Congo')], max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='+22507070707', max_length=20, null=True)),
                ('nationalite', models.CharField(blank=True, default='00000000', max_length=70, null=True)),
                ('personal_mail', models.CharField(blank=True, default='email@sah.com', max_length=70, null=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_bapteme', models.DateField(blank=True, null=True)),
                ('type_bapteme', models.CharField(blank=True, choices=[('Immersion', 'Immersion'), ('Aspersion', 'Aspersion')], max_length=100, null=True)),
                ('lieu_bapteme', models.CharField(blank=True, default='ABMCI', max_length=100, null=True)),
                ('profession', models.CharField(blank=True, default='fonctionnaire', max_length=270, null=True)),
                ('entreprise', models.CharField(blank=True, default='Ministere', max_length=270, null=True)),
                ('mensual_revenue', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('salary_currency', models.CharField(blank=True, default='CFA', max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, default='abmci/users/avartsah.jpg', null=True, upload_to='abmci/fideles')),
                ('sortie', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='slug field', null=True, unique=True, verbose_name='slug ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.department')),
                ('enfant', models.ManyToManyField(blank=True, to='fidele.fidele')),
                ('frere', models.ManyToManyField(blank=True, to='fidele.fidele')),
                ('marie_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partenair', to='fidele.fidele')),
                ('mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maternelle', to='fidele.fidele')),
                ('pere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paternelle', to='fidele.fidele')),
                ('soeur', models.ManyToManyField(blank=True, to='fidele.fidele')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fidele', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_edit_employee', 'Can edit employee'),),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='fidele.fidele'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.location')),
                ('type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.typelocation')),
            ],
        ),
        migrations.AddField(
            model_name='fidele',
            name='location',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='fidele.location'),
        ),
        migrations.CreateModel(
            name='HistoricalFidele',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('qlook_id', models.CharField(db_index=True, default=fidele.models.qlook, editable=False, max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=100, null=True)),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('MARIE', 'MARIE'), ('CELIBATAIRE', 'CELIBATAIRE'), ('CONCUBINAGE', 'CONCUBINAGE'), ('UNION LIBRE', 'UNION LIBRE'), ('VEUF ', 'VEUF')], max_length=100, null=True)),
                ('signe', models.TextField(blank=True, default='description du fidele', max_length=500, null=True)),
                ('nbr_enfants', models.IntegerField(blank=True, default='00000000', null=True)),
                ('contry', models.CharField(blank=True, choices=[("Côte d'Ivoire", "Côte d'Ivoire"), ('France', 'France'), ('Congo', 'Congo')], max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='+22507070707', max_length=20, null=True)),
                ('nationalite', models.CharField(blank=True, default='00000000', max_length=70, null=True)),
                ('personal_mail', models.CharField(blank=True, default='email@sah.com', max_length=70, null=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_bapteme', models.DateField(blank=True, null=True)),
                ('type_bapteme', models.CharField(blank=True, choices=[('Immersion', 'Immersion'), ('Aspersion', 'Aspersion')], max_length=100, null=True)),
                ('lieu_bapteme', models.CharField(blank=True, default='ABMCI', max_length=100, null=True)),
                ('profession', models.CharField(blank=True, default='fonctionnaire', max_length=270, null=True)),
                ('entreprise', models.CharField(blank=True, default='Ministere', max_length=270, null=True)),
                ('mensual_revenue', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('salary_currency', models.CharField(blank=True, default='CFA', max_length=20, null=True)),
                ('photo', models.TextField(blank=True, default='abmci/users/avartsah.jpg', max_length=100, null=True)),
                ('sortie', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='slug field', null=True, verbose_name='slug ')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fidele.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marie_a', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fidele.fidele')),
                ('mere', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fidele.fidele')),
                ('pere', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fidele.fidele')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fidele.location')),
                ('type_membre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fidele.membretype')),
            ],
            options={
                'verbose_name': 'historical fidele',
                'verbose_name_plural': 'historical fideles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='fidele',
            name='type_membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.membretype'),
        ),
    ]
