# Generated by Django 5.0.1 on 2024-01-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fidele',
            name='fonctions',
            field=models.ManyToManyField(blank=True, to='fidele.fonction'),
        ),
    ]
