# Generated by Django 5.1.3 on 2025-08-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verseofday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='verseofday',
            name='context_key',
            field=models.CharField(db_index=True, default='DEFAULT', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='verseofday',
            unique_together={('date', 'version', 'language', 'context_key')},
        ),
    ]
