# Generated by Django 5.1.3 on 2025-08-19 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0002_alter_verseofday_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verseofday',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='verseofday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='verseofday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verseofday',
            name='eglise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vods', to='fidele.eglise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verseofday',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='verseofday',
            name='language',
            field=models.CharField(default='fr', max_length=16),
        ),
        migrations.AlterField(
            model_name='verseofday',
            name='version',
            field=models.CharField(default='LSG', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='verseofday',
            unique_together={('date', 'eglise')},
        ),
        migrations.AddIndex(
            model_name='verseofday',
            index=models.Index(fields=['eglise', 'date'], name='fidele_vers_eglise__95c549_idx'),
        ),
        migrations.AddIndex(
            model_name='verseofday',
            index=models.Index(fields=['version', 'language'], name='fidele_vers_version_2eb245_idx'),
        ),
    ]
