# Generated by Django 5.0.1 on 2024-01-24 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0002_fonction_fidele_fonctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fidele',
            name='fonctions',
        ),
        migrations.AddField(
            model_name='fidele',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.fonction'),
        ),
        migrations.AddField(
            model_name='historicalfidele',
            name='fonction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fidele.fonction'),
        ),
    ]
