# Generated by Django 5.0.1 on 2024-01-26 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_participationevenement_unique_together'),
        ('fidele', '0003_remove_fidele_fonctions_fidele_fonction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuvrierPermanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='fidele.fidele')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.evenement')),
                ('ouvrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.fidele')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.fonction')),
            ],
        ),
    ]
