# Generated by Django 5.1.3 on 2025-08-19 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0003_alter_verseofday_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('version', models.CharField(default='LSG', max_length=16)),
                ('book', models.CharField(max_length=64)),
                ('chapter', models.PositiveIntegerField()),
                ('verse', models.PositiveIntegerField()),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_usages', to='fidele.eglise')),
            ],
            options={
                'indexes': [models.Index(fields=['eglise', 'used_on'], name='fidele_vers_eglise__4cb6ff_idx'), models.Index(fields=['eglise', 'book', 'chapter', 'verse'], name='fidele_vers_eglise__2fd349_idx')],
            },
        ),
    ]
