# Generated by Django 5.0.1 on 2024-01-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0004_ouvrierpermanence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrierpermanence',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.department'),
        ),
    ]
