# Generated by Django 5.0.1 on 2024-01-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0005_ouvrierpermanence_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrierpermanence',
            name='activites',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
