# Generated by Django 5.0.1 on 2024-01-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_participationevenement_unique_together'),
        ('fidele', '0006_ouvrierpermanence_activites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouvrierpermanence',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='ouvrierpermanence',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='ouvrierpermanence',
            name='event',
        ),
        migrations.CreateModel(
            name='Permanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='fidele.fidele')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.department')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.evenement')),
            ],
        ),
        migrations.AddField(
            model_name='ouvrierpermanence',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.permanence'),
        ),
    ]
