# Generated by Django 5.0.1 on 2024-01-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0007_remove_ouvrierpermanence_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrierpermanence',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
