# Generated by Django 5.0.1 on 2024-01-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0008_ouvrierpermanence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidele',
            name='eglise_origine',
            field=models.CharField(blank=True, default='ABMCI', max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='historicalfidele',
            name='eglise_origine',
            field=models.CharField(blank=True, default='ABMCI', max_length=270, null=True),
        ),
    ]
