# Generated by Django 5.0.1 on 2024-02-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0009_fidele_eglise_origine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidele',
            name='personal_mail',
            field=models.CharField(blank=True, default='email@mail.com', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='personal_mail',
            field=models.CharField(blank=True, default='email@mail.com', max_length=70, null=True),
        ),
    ]
