# Generated by Django 5.0.1 on 2024-02-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0010_alter_fidele_personal_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fidele',
            name='enfant',
        ),
    ]
