# Generated by Django 5.0.1 on 2024-02-05 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0012_eglise_fidele_eglise_historicalfidele_eglise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('mission', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.eglise')),
            ],
        ),
        migrations.AddField(
            model_name='fidele',
            name='famille_alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.familles'),
        ),
        migrations.AddField(
            model_name='historicalfidele',
            name='famille_alliance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fidele.familles'),
        ),
    ]
