# Generated by Django 5.0.1 on 2024-02-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0013_familles_fidele_famille_alliance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidele',
            name='membre',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfidele',
            name='membre',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
