# Generated by Django 5.0.1 on 2024-02-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0014_fidele_membre_historicalfidele_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidele',
            name='membre',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='membre',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
