# Generated by Django 5.0.1 on 2024-02-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0015_alter_fidele_membre_alter_historicalfidele_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemesParticulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('traitement', models.BooleanField(blank=True, default=False, null=True)),
                ('fidele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.fidele')),
            ],
        ),
        migrations.CreateModel(
            name='SujetPriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=250, null=True)),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('traitement', models.BooleanField(blank=True, default=False, null=True)),
                ('fidele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.fidele')),
            ],
        ),
    ]
