# Generated by Django 5.1.3 on 2025-07-27 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0016_problemesparticulier_sujetpriere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('ancienne_eglise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties', to='fidele.eglise')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='fidele.fidele')),
                ('nouvelle_eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees', to='fidele.eglise')),
            ],
            options={
                'verbose_name_plural': 'Historique des transferts',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
