# Generated by Django 5.1.3 on 2025-07-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidele',
            name='photo',
            field=models.ImageField(blank=True, default='abmci/users/7.png', null=True, upload_to='abmci/fideles'),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='photo',
            field=models.TextField(blank=True, default='abmci/users/7.png', max_length=100, null=True),
        ),
    ]
