# Generated by Django 5.1.3 on 2025-07-27 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0019_alter_fidele_photo_alter_historicalfidele_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anniversaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_anniversaire', models.DateField()),
                ('type_anniversaire', models.CharField(choices=[('NAISS', 'Anniversaire de naissance'), ('BAPT', 'Anniversaire de baptême'), ('MARI', 'Anniversaire de mariage'), ('CONV', 'Anniversaire de conversion')], max_length=50)),
                ('celebration_organisee', models.BooleanField(default=False)),
                ('date_celebration', models.DateField(blank=True, null=True)),
                ('cadeau', models.TextField(blank=True)),
                ('photos', models.FileField(blank=True, upload_to='anniversaires/')),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversaires', to='fidele.fidele')),
                ('participants', models.ManyToManyField(blank=True, related_name='anniversaires_participes', to='fidele.fidele')),
            ],
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conseil', models.DateTimeField()),
                ('type_conseil', models.CharField(choices=[('MAT', 'Conseil matrimonial'), ('FAM', 'Conseil familial'), ('FIN', 'Conseil financier'), ('SPI', 'Conseil spirituel'), ('PRO', 'Orientation professionnelle')], max_length=3)),
                ('sujet', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('recommandations', models.TextField()),
                ('confidential', models.BooleanField(default=True)),
                ('suivi_requis', models.BooleanField(default=False)),
                ('conseillers', models.ManyToManyField(related_name='conseils_donnes', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='conseils_recus', to='fidele.fidele')),
            ],
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(max_length=200)),
                ('cause', models.CharField(blank=True, max_length=200)),
                ('date_ceremonie', models.DateField()),
                ('lieu_ceremonie', models.CharField(max_length=200)),
                ('hommage', models.TextField(blank=True)),
                ('defunt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deces', to='fidele.fidele')),
                ('officiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceremonies_deces', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='ceremonies_deces_participes', to='fidele.fidele')),
            ],
        ),
        migrations.CreateModel(
            name='DemandePriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('sujet', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('statut', models.CharField(choices=[('ACT', 'Active'), ('REP', 'Répondue'), ('ENC', 'En cours')], default='ACT', max_length=3)),
                ('date_reponse', models.DateField(blank=True, null=True)),
                ('temoignage', models.TextField(blank=True)),
                ('publique', models.BooleanField(default=False)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_priere', to='fidele.fidele')),
                ('equipe_priere', models.ManyToManyField(blank=True, related_name='prieres_assignees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntretienPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(choices=[('SPI', 'Entretien spirituel'), ('DIS', 'Discipline'), ('ACC', 'Accompagnement'), ('CRI', 'Situation de crise')], max_length=3)),
                ('date', models.DateTimeField()),
                ('resume', models.TextField()),
                ('actions', models.TextField(blank=True)),
                ('confidential', models.BooleanField(default=False)),
                ('suivi_requis', models.BooleanField(default=False)),
                ('date_suivi', models.DateField(blank=True, null=True)),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='fidele.fidele')),
                ('pasteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_conduits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotePastorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('confidentialite', models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Privé'), ('CON', 'Confidentiel')], default='PRI', max_length=3)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_redigees', to=settings.AUTH_USER_MODEL)),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_pastorales', to='fidele.fidele')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('presence', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidele.fidele')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemeParticulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_decouverte', models.DateField()),
                ('gravite', models.CharField(choices=[('F', 'Faible'), ('M', 'Moyen'), ('E', 'Élevé'), ('C', 'Critique')], default='M', max_length=1)),
                ('statut', models.CharField(default='En cours', max_length=20)),
                ('solution', models.TextField(blank=True)),
                ('date_resolution', models.DateField(blank=True, null=True)),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes', to='fidele.fidele')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sacrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sacrement', models.CharField(choices=[('BAP', 'Baptême'), ('CEN', 'Sainte Cène'), ('MAR', 'Mariage'), ('ONC', 'Onction'), ('REC', 'Réconciliation')], max_length=3)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('documents', models.FileField(blank=True, upload_to='sacrements/')),
                ('notes', models.TextField(blank=True)),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacrements', to='fidele.fidele')),
                ('officiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sacrements_adminitres', to=settings.AUTH_USER_MODEL)),
                ('temoins', models.ManyToManyField(blank=True, related_name='sacrements_temoignes', to='fidele.fidele')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('participants', models.ManyToManyField(related_name='services_participes', through='fidele.ParticipationService', to='fidele.fidele')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fidele.fidele')),
            ],
        ),
        migrations.AddField(
            model_name='participationservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidele.service'),
        ),
        migrations.DeleteModel(
            name='ProblemesParticulier',
        ),
    ]
