# Generated by Django 5.1.3 on 2025-07-29 20:36

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0021_userprofilecompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fidele',
            name='personal_mail',
        ),
        migrations.RemoveField(
            model_name='historicalfidele',
            name='personal_mail',
        ),
        migrations.AlterField(
            model_name='fidele',
            name='contry',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='eglise_origine',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='entreprise',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='lieu_bapteme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='nationalite',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='nbr_enfants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CI'),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='profession',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fidele',
            name='signe',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='contry',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='eglise_origine',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='entreprise',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='lieu_bapteme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='nationalite',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='nbr_enfants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CI'),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='profession',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfidele',
            name='signe',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
