# Generated by Django 5.1.3 on 2025-08-12 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0022_remove_fidele_personal_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Précision de la position en mètres', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='eglise',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude en degrés décimaux (-90 à 90)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='eglise',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude en degrés décimaux (-180 à 180)', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='FidelePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('browser', 'Browser'), ('mobile_gps', 'Mobile GPS'), ('other', 'Other')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='fidele.fidele')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['fidele', 'captured_at'], name='fidele_fide_fidele__2ad03c_idx')],
            },
        ),
    ]
