# Generated by Django 5.1.3 on 2025-08-12 14:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0023_eglise_accuracy_eglise_latitude_eglise_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eglise',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='eglise',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='eglise',
            name='longitude',
        ),
        migrations.AddField(
            model_name='eglise',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
