# Generated by Django 5.1.3 on 2025-08-12 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidele', '0024_remove_eglise_accuracy_remove_eglise_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='verse_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eglise',
            name='verse_du_jour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eglise',
            name='verse_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
