# Generated by Django 5.1.3 on 2025-08-19 15:11

import django.utils.timezone
import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=event.models.eventcode, editable=False, max_length=300, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event/banner/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('is_recurrent', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('end_recurrence', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qr_code_scanned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VisiteDomicile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField()),
                ('duree', models.DurationField(help_text='Durée en heures:minutes')),
                ('type_visite', models.CharField(choices=[('PAS', 'Pastorale'), ('EVA', 'Évangélisation'), ('SUI', 'Suivi'), ('CRI', 'Crise familiale')], max_length=3)),
                ('compte_rendu', models.TextField()),
                ('actions_suivi', models.TextField(blank=True)),
                ('date_prochaine_visite', models.DateField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, upload_to='visites/')),
            ],
        ),
    ]
