# Generated by Django 5.1.3 on 2025-08-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('fidele', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.eglise'),
        ),
        migrations.AddField(
            model_name='participationevenement',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.evenement'),
        ),
        migrations.AddField(
            model_name='participationevenement',
            name='fidele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidele.fidele'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.typeevent'),
        ),
        migrations.AddField(
            model_name='visitedomicile',
            name='foyers',
            field=models.ManyToManyField(related_name='visites_recues', to='fidele.fidele'),
        ),
        migrations.AddField(
            model_name='visitedomicile',
            name='visiteurs',
            field=models.ManyToManyField(related_name='visites_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participationevenement',
            unique_together={('fidele', 'evenement')},
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['eglise', 'date_debut'], name='event_evene_eglise__25eb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['date_fin'], name='event_evene_date_fi_4f31bd_idx'),
        ),
    ]
