# Generated by Django 5.0.1 on 2024-01-18 21:36

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_evenement_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='code',
            field=models.CharField(default=event.models.eventcode, editable=False, max_length=300, unique=True),
        ),
    ]
