# Generated by Django 5.1.3 on 2025-08-26 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
        ('fidele', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='event.evenement'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='series_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['series_id'], name='event_evene_series__330386_idx'),
        ),
        migrations.AddConstraint(
            model_name='evenement',
            constraint=models.UniqueConstraint(fields=('series_id', 'date_debut', 'date_fin'), name='uniq_event_series_window'),
        ),
    ]
