# Generated by Django 5.0.1 on 2024-01-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_evenement_code'),
        ('fidele', '0002_fonction_fidele_fonctions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participationevenement',
            unique_together={('fidele', 'evenement')},
        ),
    ]
