# Generated by Django 5.0.1 on 2024-02-04 14:08

import recurrence.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_participationevenement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
