# Generated by Django 5.0.1 on 2024-02-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_evenement_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='recurrence',
        ),
    ]
