# Generated by Django 5.1.3 on 2025-07-27 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_evenement_recurrence'),
        ('fidele', '0020_competence_anniversaire_conseil_deces_demandepriere_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteDomicile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField()),
                ('duree', models.DurationField(help_text='Durée en heures:minutes')),
                ('type_visite', models.CharField(choices=[('PAS', 'Pastorale'), ('EVA', 'Évangélisation'), ('SUI', 'Suivi'), ('CRI', 'Crise familiale')], max_length=3)),
                ('compte_rendu', models.TextField()),
                ('actions_suivi', models.TextField(blank=True)),
                ('date_prochaine_visite', models.DateField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, upload_to='visites/')),
                ('foyers', models.ManyToManyField(related_name='visites_recues', to='fidele.fidele')),
                ('visiteurs', models.ManyToManyField(related_name='visites_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
