# Generated by Django 5.1.3 on 2025-08-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_visitedomicile'),
        ('fidele', '0022_remove_fidele_personal_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fidele.eglise'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='end_recurrence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='is_recurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='recurrence_rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
