# Generated by Django 5.1.3 on 2025-08-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_evenement_eglise_evenement_end_recurrence_and_more'),
        ('fidele', '0026_prayercategory_prayerrequest_prayercomment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['eglise', 'date_debut'], name='event_evene_eglise__25eb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['date_fin'], name='event_evene_date_fi_4f31bd_idx'),
        ),
    ]
