# Generated by Django 5.1.3 on 2026-05-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='format_',
            new_name='format',
        ),
        migrations.RenameIndex(
            model_name='formationmodule',
            new_name='formation_f_session_380750_idx',
            old_name='formation_f_session_8c1d3a_idx',
        ),
        migrations.RenameIndex(
            model_name='formationsession',
            new_name='formation_f_formati_d9efc2_idx',
            old_name='formation_f_formati_4b2f6e_idx',
        ),
    ]
