# Generated by Django 5.1.3 on 2025-08-15 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mariage', models.DateField()),
                ('lieu_mariage', models.CharField(max_length=200)),
                ('numero_acte', models.CharField(blank=True, max_length=50)),
                ('contrat_matrimonial', models.FileField(blank=True, upload_to='mariages/contrats/')),
                ('photos', models.FileField(blank=True, upload_to='mariages/photos/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiancailles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField()),
                ('date_ceremonie', models.DateField()),
                ('lieu_ceremonie', models.CharField(max_length=200)),
                ('sessions_conseil', models.PositiveIntegerField(default=3)),
                ('sessions_terminees', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(default='En cours', max_length=20)),
                ('documents', models.FileField(blank=True, upload_to='fiancailles/')),
                ('conseiller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiancailles_conseillees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
