# Generated by Django 5.1.3 on 2025-08-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eden', '0001_initial'),
        ('fidele', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiancailles',
            name='femme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiancailles_femme', to='fidele.fidele'),
        ),
        migrations.AddField(
            model_name='fiancailles',
            name='homme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiancailles_homme', to='fidele.fidele'),
        ),
        migrations.AddField(
            model_name='mariage',
            name='couple',
            field=models.ManyToManyField(related_name='mariages', to='fidele.fidele'),
        ),
        migrations.AddField(
            model_name='mariage',
            name='officiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mariages_officies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mariage',
            name='temoins',
            field=models.ManyToManyField(blank=True, related_name='mariages_temoignes', to='fidele.fidele'),
        ),
    ]
